### ISSUE TITLE
Architecture Documentation

### ISSUE THREAD

**Issue by rml596** [jketterl/digiham#4]
I am trying to understand where `Digiham` falls in to the architecture diagram with `Codec Server`. 

`Codec Server` is a server for access to USB codec devices? Then `Digiham` is a decoding program to send feed to `Codec Server`, `Codec Server` decodes the feed, then sends it back to `Digiham`, `Digiham` then plays it to a local speaker?

**Comment by jketterl** [comment]
Sorry, but this place is reserved for issues and not suitable for general discussion. I have opened the discussions on the codecserver repository for general request and discussions.

Also, you should not ask for an architecture diagram. Both Digiham and codecserver only provide their individual services. An architecture diagram is therefor beyond scope here.

**Comment by rml596** [comment]
I'm just trying to figure out where Digiham fits in and if its alternative to USB codec devices. I can't seem to find my answer in your documentation or code.

**Comment by jketterl** [comment]
You're asking the wrong questions in the wrong place.
