### ISSUE TITLE
P25 decoder

### ISSUE THREAD

**Issue by AsciiWolf** [jketterl/digiham#5]
**Feature description**
From [Wikipedia](https://en.wikipedia.org/wiki/Project_25): _Project 25 (P25 or APCO-25) is a suite of standards for interoperable digital two-way radio products. P25 was developed by public safety professionals in North America and has gained acceptance for public safety, security, public service, and commercial applications worldwide. P25 radios are a direct replacement for analog UHF (typically FM) radios, but add the ability to transfer data as well as voice, allowing for more natural implementations of encryption and text messaging. P25 radios are commonly implemented by dispatch organizations, such as police, fire, ambulance and emergency rescue service, using vehicle-mounted radios combined with handheld walkie-talkie use._

**Target audience**
Many radio hobbyists listen to commercial (unencrypted) P25 transmissions.

**Comment by jketterl** [comment]
Please check the project backlog at https://github.com/users/jketterl/projects/1 - P25 is already on there.

**Comment by AsciiWolf** [comment]
Oops, did not notice this. Thanks!
