### ISSUE TITLE
TETRA decoder

### ISSUE THREAD

**Issue by AsciiWolf** [jketterl/digiham#6]
**Feature description**
From [Wikipedia](https://en.wikipedia.org/wiki/Terrestrial_Trunked_Radio): _Terrestrial Trunked Radio (TETRA; formerly known as Trans-European Trunked Radio), a European standard for a trunked radio system, is a professional mobile radio and two-way transceiver specification. TETRA was specifically designed for use by government agencies, emergency services, (police forces, fire departments, ambulance) for public safety networks, rail transport staff for train radios, transport services and the military. TETRA is the European version of trunked radio, similar to Project 25._

**Target audience**
Many radio hobbyists listen to commercial (unencrypted) TETRA transmissions. TETRA is also [used](https://www.hamtetra.network) by some European hams.

**Comment by jketterl** [comment]
Please check the project backlog at https://github.com/users/jketterl/projects/1 - P25 is already on there.
