### ISSUE TITLE
Unable to install digiham via openwebrx package on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ofadam** [jketterl/digiham#8]
With the unstable Ubuntu repository at openwebrx.de, "python3-digiham" requires only python3 3.10 or lower... which means that the 3.10.4 release with Ubuntu 22.04 LTS means digiham can't be installed via package. Could it be changed to allow python3 3.10.4 or newer?

**Comment by jketterl** [comment]
The repository contains packages for Ubuntu Hirsute Hippo, which is 21.04. No, I cannot build packages that work on every Ubuntu version since the environment changes with every version.
