### ISSUE TITLE
CMake Error at CMakeLists.txt:47 (set_target_properties):

### ISSUE THREAD

**Issue by ambanmba** [jketterl/digiham#9]
I'm getting this at the `cmake ..` step

```
CMake Error at CMakeLists.txt:47 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

```

**Comment by jketterl** [comment]
The error message suggests that `${PROJECT_VERSION}` is empty, however since this is an internal variable provided by cmake itself it should be guaranteed to be available...

What is your cmake version?

**Comment by ambanmba** [comment]
cmake version 3.18.4

**Comment by jketterl** [comment]
I just tried to reproduce this on Debian Bullseye (which seems to contain that specific version of cmake) and I get no errors.

Please make sure you run the build in the root directory of the checkout. I do get the error message you have (along with a number of other warnings) when I attempt to build from the `src` directory.

**Comment by ambanmba** [comment]
🤦‍♂️ Yes, it was user error. I was not in the root directory.

It works fine from the root directory of the checkout.
